Nelder Mead Method is used for doing unconstrained non-linear optimization. It does not rely on gradient. Therefore it is intuitive and simple. However, This method is prone to the initial guess. see details in https://zhuanlan.zhihu.com/p/34295339


In [101]:
def NelderMead (func, x0, alpha = 1, gamma =2, rho =0.5, sigma =0.5, tol = 1e-5):
    n= len(x0)
    points = [x0 ]
    for i in range(0,n):
        x_new = x0.copy()
        x_new[i] = x_new[i]+ 0.01
        points.append(x_new)
   
    iter = 1
    while (1):
        if (iter>200) :
            break
        f = [func(i) for i in points ]
        fsorted= np.sort(f)
        psorted= [points[i] for i in np.argsort(f).tolist()]
        gpoint = sum(psorted[0:n])/n
        # Reflection
        rpoint = gpoint + alpha * (gpoint - psorted[n])
        f_rpoint = func(rpoint)
        if ( f_rpoint < fsorted[n-1] and f_rpoint >= fsorted[0]):
            psorted[n] = rpoint
            points = psorted
            iter = iter +1
            continue
        elif ( f_rpoint < fsorted[0]):
            # extension
            epoint = gpoint + gamma * ( rpoint - gpoint) 
            f_epoint = func(epoint)
            if (f_epoint < f_rpoint):
                psorted[n] = epoint
            else:
                psorted[n] = rpoint
            points = psorted
            iter = iter+1
            continue
        elif ( f_rpoint >= fsorted [n-1] and f_rpoint < fsorted[n]):
            # contraction
            cpoint = gpoint + rho * ( rpoint -gpoint)
            f_cpoint = func (cpoint)
            if (f_cpoint < f_rpoint):
                psorted [n] = cpoint
                points = psorted
                iter = iter +1
                continue
        elif (f_rpoint >= fsorted[n]):
            cpoint = gpoint +rho *(psorted[n] - gpoint)
            f_cpoint = func (cpoint)
            if (f_cpoint < fsorted [n]):
                psorted [n] = cpoint
                points = psorted
                iter = iter + 1
                continue

        points = [ psorted[0]+sigma*(i - psorted[0])  for i in psorted  ]
        if (np.linalg.norm(points[0]-points[n])<tol or iter >200):
            break
        iter = iter +1

    return points

In [104]:
import numpy as np
from statistics import math
def calc4(numbers):
    x,y,z= numbers[0],numbers[1],numbers[2]
    return (x-1)**2 +(y-5)**2 + (z-3)**2 + x*z

# test 
NelderMead(calc4, np.array([1,1,1], dtype =float))

[array([-0.66666667,  4.99999998,  3.33333333]),
 array([-0.66666666,  4.99999999,  3.33333332]),
 array([-0.66666667,  5.        ,  3.33333334]),
 array([-0.66666667,  4.99999999,  3.33333333])]